# Generated by Django 4.2.2 on 2023-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', '客戶'), ('employee', '員工'), ('manager', '主管')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='news_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion_notification',
            field=models.BooleanField(default=False),
        ),
    ]
