# Generated by Django 4.2.2 on 2023-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_role_alter_user_activity_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
