# Generated by Django 4.2.2 on 2023-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_sales_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default category', max_length=100),
        ),
    ]
